# Stop Words in Spacy :

In [1]:
import spacy

In [5]:
from spacy.lang.en.stop_words import STOP_WORDS

print(STOP_WORDS)

{'but', 'both', 'even', 'now', 'hereupon', 'therein', 'four', 'nowhere', 'such', 'are', 'ours', 'too', 'can', 'no', '‘s', 'really', 'also', 'nine', 'that', 'namely', '‘ll', 'eleven', 'doing', 'him', 'quite', 'nor', 'without', 'say', 'via', 'do', 'yours', "'d", 'becoming', 'except', 'well', 'whole', 'become', 'herself', 'whether', 'under', 'hundred', 'used', 'from', 'everything', 'see', '‘m', 'one', 'itself', 'again', '’re', 'amongst', 'thus', 'how', 'never', 'forty', 'these', 'fifteen', 'ever', 'while', 'thereby', 'nobody', 'the', 'seem', 'will', 'front', 'any', 'whereas', 'part', 'side', 'among', 'somewhere', 'anyone', 'have', 'seems', 'three', 'whoever', 'thereupon', 'using', 'who', "'ve", 'be', 'twelve', 'n‘t', "'re", 'you', 'cannot', 'here', 'two', 'to', 'been', 'something', 'due', 'until', 'by', 'go', 'yourself', 'we', 'none', 'though', 'show', '‘d', 'being', 'became', 'get', 'serious', 'take', 'because', 'several', 'few', 'throughout', 'beforehand', 'always', 'whereby', 'there', 'between', 'their', 'or', 'together', 'an', 'this', 'why', 'for', 'very', 'must', 'than', 'since', 'beyond', 'becomes', 'could', 'most', '’s', 'whom', 'which', 'am', 'onto', 'in', 'everywhere', 'at', 'further', '‘ve', 'every', 'nothing', '’ve', 'much', "'ll", 'already', 'my', 'on', 'behind', 'indeed', 'alone', 'me', 'noone', '’ll', 'sometimes', 'seeming', 'unless', 'they', 'was', 'fifty', 'whenever', 'six', 'bottom', 'of', 'ourselves', 'so', 'has', 'had', 'hereby', 'beside', 'hers', 'is', 'next', 'meanwhile', 'hereafter', 'still', 'everyone', 'some', 'herein', 'himself', 'first', 'more', 'eight', 'thence', 'does', 'each', 'others', 'keep', 'call', 'mine', 'yourselves', 'made', 'about', "'s", 'either', 'during', 'should', 'may', 'whereupon', 'she', 'below', 'latterly', 'just', 'someone', 'us', 'after', 'its', 'above', 'done', 'themselves', 'along', 'toward', 'our', 'towards', 'within', 'last', 'hence', 'whereafter', 'various', 'i', 'thereafter', 'third', 'mostly', '‘re', 'wherein', 'out', 'else', 'ca', 'however', 'besides', 'anyway', 'down', 'regarding', 're', 'not', 'neither', 'same', 'give', 'then', 'those', 'ten', 'n’t', 'nevertheless', 'per', 'he', 'another', 'once', 'less', 'enough', 'across', 'if', '’d', 'seemed', 'when', 'other', 'it', 'somehow', 'move', 'did', 'formerly', 'elsewhere', 'whatever', 'thru', 'would', 'moreover', 'as', "n't", 'before', 'full', 'latter', 'what', 'all', 'into', 'many', 'twenty', 'might', 'five', 'often', 'only', 'perhaps', 'amount', 'where', 'whose', 'off', 'anywhere', 'whither', 'yet', 'otherwise', 'name', 'up', '’m', 'and', 'although', 'against', 'least', 'myself', 'almost', 'were', 'over', 'make', 'top', 'through', 'wherever', 'put', 'please', 'his', 'with', 'anyhow', "'m", 'empty', 'sometime', 'your', 'whence', 'rather', 'sixty', 'around', 'therefore', 'a', 'afterwards', 'former', 'anything', 'own', 'back', 'them', 'upon', 'her'}

# Identifying Stop Words in Spacy :

In [17]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("we just open our wings, the flying part is comming soon.")

print("stop words are :")
for token in doc:
    if token.is_stop:
        print(token)

stop words are :
we
just
our
the
part
is

# Stop Words Removal in Spacy :

creating a function for removing stop words

In [31]:
def preprocess_stop_words(text):
    doc = nlp(text)

    no_stop_words = [token.text for token in doc if not token.is_stop and not token.is_punct]
    return no_stop_words

In [33]:
preprocess_stop_words("my name is the vaishnav wagh.")

['vaishnav', 'wagh']

In [35]:
preprocess_stop_words("python for machine learning and data science")

['python', 'machine', 'learning', 'data', 'science']

# Text Cleaning by removing stop words :

In [44]:
import pandas as pd

df = pd.read_json("C:/Users/Vaishnav/Downloads/course/NLP/combined.json",lines=True)

df.head(10)

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
5,None,105 Individuals Indicted for Violating the RIC...,A nine count federal indictment was unsealed t...,2015-07-22T00:00:00-04:00,[],[USAO - Puerto Rico]
6,14-032,12th Former Officer at Roxbury Correctional In...,"Michael Morgan, formerly an officer at Roxbury...",2014-01-10T00:00:00-05:00,[],"[Civil Rights Division, Civil Rights - Crimina..."
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
8,14-849,14 Individuals Charged with Trafficking Identi...,Fourteen individuals were charged in three ...,2014-08-12T00:00:00-04:00,[],[Criminal Division]
9,15-089,"15th Member of Washington, D.C.-Based Identity...",Defendant Admits To Targeting Parents Of Hospi...,2015-01-23T00:00:00-05:00,[],[Criminal Division]

In [60]:
df = df[df["topics"].str.len() != 0 ]

df.sample(5)

,id,title,contents,date,topics,components
4042,16-630,Former Fugitive Convicted of Kidnapping and Al...,A former fugitive who was illegally residing i...,2016-05-31T00:00:00-04:00,"[Human Smuggling, Immigration, Violent Crime]","[Criminal Division, USAO - Texas, Southern]"
7363,16-948,Justice Department Settles Immigration-Related...,The Justice Department reached an agreement to...,2016-08-15T00:00:00-04:00,"[Civil Rights, Immigration]","[Civil Rights Division, Civil Rights - Immigra..."
4171,13-1265,Former KKK Leader Indicted for Cross Burning i...,"Steven Joshua Dinkle, former Exalted Cyclops o...",2013-11-29T00:00:00-05:00,[Hate Crimes],"[Civil Rights Division, Civil Rights - Crimina..."
5929,15-334,Justice Department and New York Attorney Gener...,The Department of Justice and New York State A...,2015-03-16T00:00:00-04:00,[Antitrust],[Antitrust Division]
11467,15-274,Three Defendants Charged with One of the Large...,One Of The Defendants Has Already Pleaded Guil...,2015-03-06T00:00:00-05:00,[Cyber Crime],[Criminal Division]

In [66]:
print("shape of the dataset :",df.shape)

shape of the dataset : (4688, 6)

In [68]:
df = df.head(100)
df.shape

(100, 6)

In [70]:
df.contents.iloc[5]

'Twenty-one members of a massive India-based fraud and money laundering conspiracy that defrauded thousands of U.S. residents of hundreds of millions of dollars were sentenced this week to terms of imprisonment up to 20 years.\xa0 Three other conspirators were sentenced earlier this year for laundering proceeds for the conspiracy, which was operated out of India-based call centers that targeted U.S. residents in various telephone fraud schemes.\xa0 This week’s sentencing hearings took place in Houston, Texas, before the Honorable David Hittner of the Southern District of Texas.\xa0\xa0\xa0 \xa0\xa0\xa0 Attorney General Jeff Sessions of the U.S. Department of Justice, Assistant Attorney General Brian A. Benczkowski of the Justice Department’s Criminal Division, U.S. Attorney Ryan Patrick of the Southern District of Texas, Acting Executive Associate Director Derek N. Benner of U.S. Immigration and Customs Enforcement’s (ICE) Homeland Security Investigations (HSI), Inspector General J. Russell George of the U.S. Treasury Inspector General for Tax Administration (TIGTA), and Special Agent in Charge David Green of the U.S. Department of Homeland Security (DHS) Office of Inspector General (OIG) Houston, Texas made the announcement today. “The stiff sentences imposed this week represent the culmination of the first-ever large scale, multi-jurisdiction prosecution targeting the India call center scam industry,” said Attorney General Sessions.\xa0 “This case represents one of the most significant victories to date in our continuing efforts to combat elder fraud and the victimization of the most vulnerable members of the U.S. public.\xa0 The transnational criminal ring of fraudsters and money launderers who conspired to bilk older Americans, legal immigrants and many others out of their life savings through their lies, threats and financial schemes must recognize that all resources at the Department’s disposal will be deployed to shut down these telefraud schemes, put those responsible in jail, and bring a measure of justice to the victims.” “This type of fraud is sickening,” said U.S. Attorney Patrick. \xa0“However, after years of investigation and incredible hard work by multiple agents and attorneys, these con artists are finally headed to prison. Their cruel tactics preyed on some very vulnerable people, thereby stealing millions from them. These sentences should send a strong message that we will follow the trail no matter how difficult and seek justice for those victimized by these types of transnational schemes. We will simply not stand by and allow criminals to use the names of legitimate government agencies to enrich themselves by victimizing others.” “Today’s sentences should serve as a strong deterrent to anyone considering taking part in similar scams, and I hope that they provide a sense of justice to the victims, as well,” said HSI Acting Executive Associate Director Derek N. Benner.\xa0 “There is no safe haven from U.S. law enforcement. HSI will continue to utilize our unique investigative mandate, in conjunction with our local, state, and federal partners, to attack and dismantle the criminal enterprises who would seek to manipulate U.S. institutions and taxpayers.” “The sentences imposed on these defendants validate our efforts to bring to justice scammers who defraud taxpayers by impersonating employees of the Internal Revenue Service,” said Inspector General J. Russell George. \xa0“I wish to thank the Department of Justice, the multiple federal agencies involved, and most importantly, my own investigators who continue to devote countless hours to these cases. \xa0Taxpayers must remain wary of unsolicited telephone calls from individuals claiming to be IRS employees.\xa0 If any taxpayer believes they or someone they know is a victim of an IRS impersonation scam, they should report it to TIGTA at www.tigta.gov or by calling 1-800-366-4484.” “The sentences imposed this week provide a clear deterrent to those who would seek to enrich themselves by extorting the most vulnerable in our society,” said DHS-OIG Special Agent in Charge Green.\xa0 “These scammers should know that their actions carry real consequences, both for their victims and for themselves, and that there are dedicated agents and prosecutors who will go above and beyond to find them, identify them and hold them accountable for their crimes.” Miteshkumar Patel, 42, of Illinois, was sentenced to serve 240 months in prison followed by three years of supervised release on the charge of money laundering conspiracy.\xa0 According to the factual basis of his plea agreement, Patel served as the manager of a Chicago-based crew of “runners” that liquidated and laundered fraud proceeds generated by callers at India-based call centers.\xa0 Those callers used call scripts and lead lists to target victims throughout the United States with telefraud schemes in which the callers impersonated U.S. government employees from the IRS and U.S. Citizenship and Immigration Services (USCIS).\xa0 The callers duped victims into believing that they owed money to the U.S. government and would be arrested or deported if they did not pay immediately.\xa0 After the victims transferred money to the callers, a network of U.S.-based runners moved expeditiously to liquidate and launder fraud proceeds through the use of anonymous stored value cards.\xa0 In addition to recruiting, training, and tasking runners in his crew, Patel also coordinated directly with the Indian side of the conspiracy about the operation of the scheme.\xa0 Patel was held accountable for laundering between $9.5 and $25 million for the scheme. \xa0\xa0\xa0 Hardik Patel, 31, of Illinois, was sentenced to serve 188 months in prison followed by three years of supervised release on the charge of wire fraud conspiracy.\xa0 Hardik consented to removal to India upon completion of his prison term.\xa0 According to the factual basis of his plea agreement, Patel was a co-owner and manager of an India-based call center involved in the conspiracy.\xa0 In addition to managing the day-to-day operations of a call center, Patel also processed payments and did bookkeeping for the various call centers involved in the fraud scheme.\xa0 One of the India-based co-defendants with whom Patel communicated about the scheme was Sagar “Shaggy” Thakar, a payment processor that Indian authorities arrested in April 2017 in connection with call center fraud.\xa0 After moving to the United States in 2015, Patel continued to promote the conspiracy by recruiting runners to liquidate fraud proceeds.\xa0 Patel was held accountable for laundering between $3.5 and $9.5 million dollars for the scheme.\xa0 Sunny Joshi, aka Sharad Ishwarlal Joshi and Sunny Mahashanker Joshi, 47, of Texas, was sentenced to serve 151 months in prison on the charge of money laundering conspiracy, and 120 months in prison on the charge of naturalization fraud to run concurrent followed by three years of supervised release.\xa0 According to the factual basis of his plea agreement, Joshi was a member of a Houston-based crew of runners that he co-managed with his brother, co-defendant Mike Joshi, aka Rajesh Bhatt.\xa0 Sunny Joshi communicated extensively with India-based co-defendants about the operations of the scheme, and was held accountable for laundering between $3.5 and $9.5 million.\xa0 Additionally, in connection with his sentence on the immigration charge, Judge Hittner entered an order revoking Joshi’s U.S. citizenship and requiring him to surrender his certificate of naturalization.\xa0 \xa0\xa0\xa0\xa0 Twenty-two of the defendants sentenced before Judge Hittner were held jointly and severally liable for restitution of $8,970,396 payable to identified victims of their crimes.\xa0 Additionally, the court entered individual preliminary orders of forfeiture against 21 defendants for assets that were seized in the case, and money judgments totaling over $72,942,300. Eighteen other defendants were also sentenced in Houston before Judge Hittner this week: In addition to these 21 defendants, three others were previously sentenced for their involvement in the same fraud and money laundering scheme: According to various admissions made in connection with the defendants’ guilty pleas, between 2012 and 2016, the defendants and their conspirators perpetrated a complex fraud and money laundering scheme in which individuals from call centers located in Ahmedabad, India, frequently impersonated officials from the IRS or USCIS in a ruse designed to defraud victims located throughout the United States.\xa0 Using information obtained from data brokers and other sources, call center operators targeted U.S. victims who were threatened with arrest, imprisonment, fines or deportation if they did not pay alleged monies owed to the government.\xa0 Victims who agreed to pay the scammers were instructed how to provide payment, including by purchasing stored value cards or wiring money.\xa0 Once a victim provided payment, the call centers turned to a network of runners based in the United States to liquidate and launder the extorted funds as quickly as possible by purchasing reloadable cards or retrieving wire transfers. \xa0In a typical scenario, call centers directed runners to purchase these stored value reloadable cards and transmit the unique card number to India-based co-conspirators who registered the cards using the misappropriated personal identifying information (PII) of U.S. citizens.\xa0 The India-based co-conspirators then loaded these cards with scam funds obtained from victims.\xa0 The runners used the stored value cards to purchase money orders that they deposited into the bank account of another person.\xa0 For their services, the runners would earn a specific fee or a percentage of the funds.\xa0 Runners also received victims’ funds via wire transfers, which were retrieved under fake names and through the use of using false identification documents, direct bank deposits by victims, and Apple iTunes or other gift cards that victims purchased.\xa0 The indictment in this case also charged 32 India-based conspirators and five India-based call centers with general conspiracy, wire fraud conspiracy, and money laundering conspiracy.\xa0 These defendants have yet to be arraigned in this case.\xa0 An indictment is merely an allegation and the defendants are presumed innocent until proven guilty beyond a reasonable doubt in a court of law. HSI, DHS-OIG, and TIGTA led the investigation of this case. \xa0Also providing significant support were: the Criminal Division’s Office of International Affairs; the Ft. Bend, Texas, County Sheriff’s Department; the Hoffman Estates, Illinois, Police Department; the Leonia, New Jersey, Police Department; the Naperville, Illinois, Police Department; the San Diego County District Attorney’s Office Family Protection/Elder Abuse Unit; the U.S. Secret Service; U.S. Small Business Administration Office of Inspector General; IOC-2; INTERPOL Washington; USCIS; U.S. State Department’s Diplomatic Security Service; and the U.S. Attorney’s Offices of the Northern District of Alabama, District of Arizona, Central District of California, Northern District of California, District of Colorado, Northern District of Florida, Middle District of Florida, Northern District of Georgia, Northern District of Illinois, Northern District of Indiana, Eastern District of Louisiana, District of Nevada, and the District of New Jersey. \xa0The Federal Communications Commission’s Enforcement Bureau provided assistance in TIGTA’s investigation.\xa0 Additionally, the Executive Office for U.S. Attorneys (EOUSA), Legal and Victim Programs, provided significant support to the prosecution.\xa0 Senior Trial Attorney Michael Sheckels and Trial Attorney Mona Sahaf of the Criminal Division’s Human Rights and Special Prosecutions Section (HRSP), Trial Attorney Amanda S. Wick of the Criminal Division’s Money Laundering and Asset Recovery Section, and Assistant U.S. Attorneys Mark McIntyre and Craig Feazel of the Southern District of Texas prosecuted the case.\xa0 Kaitlin Gonzalez of HRSP was the paralegal for this case.\xa0\xa0\xa0 \xa0\xa0\xa0 A Department of Justice website has been established to provide information about the case to already identified and potential victims, and the public. \xa0Anyone who believes they may be a victim of fraud or identity theft in relation to this investigation or other telefraud scam phone calls may contact the FTC via this website. Anyone who wants additional information about telefraud scams generally, or preventing identity theft or fraudulent use of their identity information, may obtain helpful information on the IRS tax scams website, the FTC phone scam website and the FTC identity theft website.\xa0'

In [72]:
len(df.contents.iloc[5])

12617

In [74]:
df["contents_new"] = df["contents"].apply(preprocess_stop_words)

In [78]:
df.head(5)

,id,title,contents,date,topics,components,contents_new
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division],"[U.S., Department, Justice, U.S., Environmenta..."
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division],"[131, count, criminal, indictment, unsealed, t..."
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U...","[United, States, Attorney, Office, Middle, Dis..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division],"[21st, Century, Oncology, LLC, agreed, pay, $,..."
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]","[21st, Century, Oncology, Inc., certain, subsi..."

#### Length of content before removing stop words

In [97]:
len(df.contents.iloc[5])

12617

#### Length of content after removing stop words

In [88]:
len(df.contents_new.iloc[5])

1202